version: 2
updates:
  - package-ecosystem: "docker"
    directory: /certbot/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "docker"
    directory: /db/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "docker"
    directory: /logging/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "docker"
    directory: /nginx/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "docker"
    directory: /node-ronc-li/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "docker"
    directory: /node-roncli-com/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "docker"
    directory: /redis/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "npm"
    directory: /logging/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "npm"
    directory: /node-ronc-li/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "npm"
    directory: /node-roncli-com/
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
