version: "3.7"

services:

  logging:
    container_name: roncli-logging
    build: ./logging
    ports:
      - "12201:12201/udp"
    environment:
      PORT: 12201
      APPINSIGHTS_PERFORMANCE_METRICS: 0
      APPINSIGHTS_INSTRUMENTATIONKEY: /run/secrets/APPINSIGHTS_INSTRUMENTATIONKEY
      APPLICATION: roncli.com
    secrets:
      - APPINSIGHTS_INSTRUMENTATIONKEY
    restart: always
    entrypoint: /var/logging/start.sh

  db:
    container_name: roncli-db
    build: ./db
    depends_on:
      - logging
    networks:
      - roncli.com-network
    ports:
      - "27017:27017"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      MONGO_INITDB_DATABASE: roncli
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGO_INITDB_ROOT_USERNAME_FILE
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_INITDB_ROOT_PASSWORD_FILE
      WEB_RONCLI_PASSWORD_FILE: /run/secrets/WEB_RONCLI_PASSWORD_FILE
    secrets:
      - MONGO_INITDB_ROOT_USERNAME_FILE
      - MONGO_INITDB_ROOT_PASSWORD_FILE
      - WEB_RONCLI_PASSWORD_FILE
    restart: always
    volumes:
      - /mnt/db:/data/db:rw
      - /mnt/backup:/data/backup:rw
    entrypoint: /var/mongo/start.sh
    privileged: true

  redis:
    container_name: roncli-redis
    build: ./redis
    depends_on:
      - logging
    networks:
      - roncli.com-network
    ports:
      - "6379:6379"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/REDIS_PASSWORD_FILE
      REDIS_PORT: 6379
    secrets:
      - REDIS_PASSWORD_FILE
    restart: always
    entrypoint: /var/redis/start.sh
    privileged: true

  node-roncli-com:
    container_name: roncli-node-roncli-com
    build: ./node-roncli-com
    depends_on:
      - logging
      - db
      - redis
    networks:
      - roncli.com-network
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: /run/secrets/APPINSIGHTS_INSTRUMENTATIONKEY
      BLIZZARD_CLIENT_ID_FILE: /run/secrets/BLIZZARD_CLIENT_ID_FILE
      BLIZZARD_CLIENT_SECRET_FILE: /run/secrets/BLIZZARD_CLIENT_SECRET_FILE
      BLOGGER_BLOG_ID: 10934322
      COOKIE_SECRET_FILE: /run/secrets/COOKIE_SECRET_FILE
      ENCRYPTION_KEY_FILE: /run/secrets/ENCRYPTION_KEY_FILE
      GITHUB_TOKEN_FILE: /run/secrets/GITHUB_TOKEN_FILE
      GOOGLE_API_KEY_FILE: /run/secrets/GOOGLE_API_KEY_FILE
      MINIFY_CACHE: 1
      MINIFY_ENABLED: 1
      NODE_ENV: production
      PHOTOS_URL: https://photos.roncli.com
      PORT: 3030
      REDIS_PASSWORD_FILE: /run/secrets/REDIS_PASSWORD_FILE
      REDIS_PORT: 6379
      REDIS_PREFIX: roncli
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_USERNAME: roncli@gmail.com
      SMTP_PASSWORD_FILE: /run/secrets/SMTP_PASSWORD_FILE
      SOUNDCLOUD_CLIENT_ID_FILE: /run/secrets/SOUNDCLOUD_CLIENT_ID_FILE
      SOUNDCLOUD_CLIENT_SECRET_FILE: /run/secrets/SOUNDCLOUD_CLIENT_SECRET_FILE
      STEAM_API_KEY_FILE: /run/secrets/STEAM_API_KEY_FILE
      STEAM_ID: 76561197996696153
      TUMBLR_CONSUMER_KEY_FILE: /run/secrets/TUMBLR_CONSUMER_KEY_FILE
      TUMBLR_CONSUMER_SECRET_FILE: /run/secrets/TUMBLR_CONSUMER_SECRET_FILE
      TUMBLR_URL: roncli.tumblr.com
      WEB_RONCLI_PASSWORD_FILE: /run/secrets/WEB_RONCLI_PASSWORD_FILE
      XIVAPI_API_KEY_FILE: /run/secrets/XIVAPI_API_KEY_FILE
    secrets:
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - BLIZZARD_CLIENT_ID_FILE
      - BLIZZARD_CLIENT_SECRET_FILE
      - COOKIE_SECRET_FILE
      - ENCRYPTION_KEY_FILE
      - GITHUB_TOKEN_FILE
      - GOOGLE_API_KEY_FILE
      - REDIS_PASSWORD_FILE
      - SMTP_PASSWORD_FILE
      - SOUNDCLOUD_CLIENT_ID_FILE
      - SOUNDCLOUD_CLIENT_SECRET_FILE
      - STEAM_API_KEY_FILE
      - TUMBLR_CONSUMER_KEY_FILE
      - TUMBLR_CONSUMER_SECRET_FILE
      - WEB_RONCLI_PASSWORD_FILE
      - XIVAPI_API_KEY_FILE
    restart: always
    volumes:
      - /mnt/files:/var/www/files:rw
    entrypoint: /var/www/start.sh
    privileged: true

  node-ronc-li:
    container_name: roncli-node-ronc-li
    build: ./node-ronc-li
    depends_on:
      - logging
      - db
      - redis
    networks:
      - roncli.com-network
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: /run/secrets/APPINSIGHTS_INSTRUMENTATIONKEY
      NODE_ENV: production
      PORT: 3031
      WEB_RONCLI_PASSWORD_FILE: /run/secrets/WEB_RONCLI_PASSWORD_FILE
    secrets:
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - WEB_RONCLI_PASSWORD_FILE
    restart: always
    entrypoint: /var/www/start.sh
    privileged: true

  nginx:
    container_name: roncli-nginx
    build: ./nginx
    depends_on:
      - node-roncli-com
      - node-ronc-li
      - logging
    networks:
      - roncli.com-network
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      PHOTOS_PASSWORD_FILE: /run/secrets/PHOTOS_PASSWORD_FILE
      PHOTOS_USERNAME_FILE: /run/secrets/PHOTOS_USERNAME_FILE
    secrets:
      - PHOTOS_PASSWORD_FILE
      - PHOTOS_USERNAME_FILE
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
      - nginx-work:/var/nginx/work:rw
    entrypoint: /var/nginx/start.sh

  certbot:
    container_name: roncli-certbot
    build: ./certbot
    depends_on:
      - nginx
      - logging
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      DOMAIN: roncli.com,photos.roncli.com,ronc.li
      EMAIL: roncli@roncli.com
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
    entrypoint: /var/certbot/start.sh

  photoprism:
    container_name: roncli-photoprism
    build: ./photoprism
    depends_on:
      - mariadb
      - logging
    networks:
      - roncli.com-network
    ports:
      - "2342:2342"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
      PHOTOPRISM_DATABASE_SERVER: mariadb:3306
      PHOTOPRISM_DOWNLOAD_TOKEN: public
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_LOG_LEVEL: error
      PHOTOPRISM_PUBLIC: "true"
      PHOTOPRISM_SITE_AUTHOR: Ronald M. Clifford
      PHOTOPRISM_SITE_CAPTION: Music. Coding. Gaming. Life.
      PHOTOPRISM_SITE_TITLE: roncli.com Photos
      PHOTOPRISM_SITE_URL: https://photos.roncli.com/
    secrets:
      - MYSQL_PASSWORD_FILE
    restart: always
    volumes:
      - /mnt/library:/photoprism/originals
      - /mnt/storage:/photoprism/storage
    entrypoint: /var/photoprism/start.sh

  mariadb:
    container_name: roncli-mariadb
    build: ./mariadb
    depends_on:
      - logging
    networks:
      - roncli.com-network
    ports:
      - "3306:3306"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      MYSQL_DATABASE: photoprism
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD_FILE
      MYSQL_USER: photoprism
    secrets:
      - MYSQL_PASSWORD_FILE
      - MYSQL_ROOT_PASSWORD_FILE
    restart: always
    volumes:
      # TODO: Use /mnt/mariadb when https://jira.mariadb.org/browse/MDEV-26970 is resolved.
      - /mnt/mariadb_local:/var/lib/mysql:rw
    entrypoint: /var/mariadb/start.sh

  mail:
    container_name: roncli-mail
    build: ./mail
    depends_on:
      - logging
    networks:
      - roncli.com-network
    ports:
      - "25:25"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      DOMAIN: roncli.com
      SMF_CONFIG: "@roncli.com:roncli@gmail.com"
      SMF_RELAYHOST: smtp.gmail.com:587
      SMTP_USERNAME: roncli@gmail.com
      SMTP_PASSWORD_FILE: /run/secrets/SMTP_PASSWORD_FILE
    secrets:
      - SMTP_PASSWORD_FILE
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - mail-dkim:/var/db/dkim:rw
    entrypoint: /var/mail/start.sh

networks:
  roncli.com-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-work:
  mail-dkim:
  nginx-work:

secrets:
  APPINSIGHTS_INSTRUMENTATIONKEY:
    file: ./secrets/APPINSIGHTS_INSTRUMENTATIONKEY
  BLIZZARD_CLIENT_ID_FILE:
    file: ./secrets/BLIZZARD_CLIENT_ID_FILE
  BLIZZARD_CLIENT_SECRET_FILE:
    file: ./secrets/BLIZZARD_CLIENT_SECRET_FILE
  COOKIE_SECRET_FILE:
    file: ./secrets/COOKIE_SECRET_FILE
  ENCRYPTION_KEY_FILE:
    file: ./secrets/ENCRYPTION_KEY_FILE
  GITHUB_TOKEN_FILE:
    file: ./secrets/GITHUB_TOKEN_FILE
  GOOGLE_API_KEY_FILE:
    file: ./secrets/GOOGLE_API_KEY_FILE
  MONGO_INITDB_ROOT_PASSWORD_FILE:
    file: ./secrets/MONGO_INITDB_ROOT_PASSWORD_FILE
  MONGO_INITDB_ROOT_USERNAME_FILE:
    file: ./secrets/MONGO_INITDB_ROOT_USERNAME_FILE
  MYSQL_PASSWORD_FILE:
    file: ./secrets/MYSQL_PASSWORD_FILE
  MYSQL_ROOT_PASSWORD_FILE:
    file: ./secrets/MYSQL_ROOT_PASSWORD_FILE
  PHOTOS_USERNAME_FILE:
    file: ./secrets/PHOTOS_USERNAME_FILE
  PHOTOS_PASSWORD_FILE:
    file: ./secrets/PHOTOS_PASSWORD_FILE
  REDIS_PASSWORD_FILE:
    file: ./secrets/REDIS_PASSWORD_FILE
  SMTP_PASSWORD_FILE:
    file: ./secrets/SMTP_PASSWORD_FILE
  SOUNDCLOUD_CLIENT_ID_FILE:
    file: ./secrets/SOUNDCLOUD_CLIENT_ID_FILE
  SOUNDCLOUD_CLIENT_SECRET_FILE:
    file: ./secrets/SOUNDCLOUD_CLIENT_SECRET_FILE
  STEAM_API_KEY_FILE:
    file: ./secrets/STEAM_API_KEY_FILE
  TUMBLR_CONSUMER_KEY_FILE:
    file: ./secrets/TUMBLR_CONSUMER_KEY_FILE
  TUMBLR_CONSUMER_SECRET_FILE:
    file: ./secrets/TUMBLR_CONSUMER_SECRET_FILE
  WEB_RONCLI_PASSWORD_FILE:
    file: ./secrets/WEB_RONCLI_PASSWORD_FILE
  XIVAPI_API_KEY_FILE:
    file: ./secrets/XIVAPI_API_KEY_FILE
