#!/bin/sh

# Validation.
if [ ! $APPINSIGHTS_INSTRUMENTATIONKEY ];
then
    echo "Warning: Application Insights is not setup.  Application will log to console."
fi

if [ $USE_AZURE_FILE_STORAGE -eq 1 ];
then
    # Mount Azure Storage file share.
    mount -t cifs $(cat $FILES_URI) /mnt/files -o vers=3.0,username=$(cat $FILES_USERNAME),password=$(cat $FILES_PASSWORD),dir_mode=0755,file_mode=0755,serverino
fi

# Run app.
APPINSIGHTS_INSTRUMENTATIONKEY=$(cat $APPINSIGHTS_INSTRUMENTATIONKEY) BLIZZARD_CLIENT_ID=$(cat $BLIZZARD_CLIENT_ID_FILE) BLIZZARD_CLIENT_SECRET=$(cat $BLIZZARD_CLIENT_SECRET_FILE) COOKIE_SECRET=$(cat $COOKIE_SECRET_FILE) ENCRYPTION_KEY=$(cat $ENCRYPTION_KEY_FILE) GITHUB_TOKEN=$(cat $GITHUB_TOKEN_FILE) GOOGLE_API_KEY=$(cat $GOOGLE_API_KEY_FILE) REDIS_PASSWORD=$(cat $REDIS_PASSWORD_FILE) SMTP_PASSWORD=$(cat $SMTP_PASSWORD_FILE) SOUNDCLOUD_CLIENT_ID=$(cat $SOUNDCLOUD_CLIENT_ID_FILE) SOUNDCLOUD_CLIENT_SECRET=$(cat $SOUNDCLOUD_CLIENT_SECRET_FILE) TUMBLR_CONSUMER_KEY=$(cat $TUMBLR_CONSUMER_KEY_FILE) TUMBLR_CONSUMER_SECRET_FILE=$(cat $TUMBLR_CONSUMER_SECRET_FILE) WEB_RONCLI_PASSWORD=$(cat $WEB_RONCLI_PASSWORD_FILE) XIVAPI_API_KEY=$(cat $XIVAPI_API_KEY_FILE) node index
